// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxC15WeY31TEKnw9wonpQ2BRZwn_5DO5g',
    appId: '1:528360537954:android:02c1e14dd2162e79fe363b',
    messagingSenderId: '528360537954',
    projectId: 'minecraft-t',
    databaseURL: 'https://minecraft-t-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'minecraft-t.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeV6MvK-97mWwPlaWTOkld0N33GjJGkZw',
    appId: '1:528360537954:ios:15d535c9f15247f8fe363b',
    messagingSenderId: '528360537954',
    projectId: 'minecraft-t',
    databaseURL: 'https://minecraft-t-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'minecraft-t.appspot.com',
    iosClientId: '528360537954-7q8rl0dh5l9vudllf5ukd32rchajujrk.apps.googleusercontent.com',
    iosBundleId: 'com.vchertuk.min-mods',
  );
}
